
version: '3'
services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: docker/Dockerfile.reactapp
    volumes:
      - ./build:/app/build
    command: ["npm", "run", "build"]
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  apache-server:
    container_name: apache
    build:
      context: .
      dockerfile: docker/Dockerfile.apache
    volumes:
      - ./build:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
    depends_on:
      - react-app
